#!/usr/bin/env node

/**
 * Environment Profile Loader
 *
 * Usage:
 *   npm run load:env -- --profile production --domain net
 *   npm run load:env -- --profile local
 *
 * Loads environment variables from .env.profiles/ based on profile and domain.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
// __dirname = .../web/scripts, so parent is .../web
const webRoot = dirname(__dirname);

function parseArgs() {
  const args = process.argv.slice(2);
  const result = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith("--")) {
      const key = args[i].slice(2);
      result[key] = args[i + 1];
      i++;
    }
  }
  return result;
}

function loadProfileEnv(profile, domain = null) {
  const profilesDir = resolve(webRoot, ".env.profiles");
  const envFiles = [];

  // Base profile (e.g., "production.env" or "local.env")
  envFiles.push(resolve(profilesDir, `${profile}.env`));

  // Domain-specific override (e.g., "production.net.env")
  if (domain) {
    envFiles.push(resolve(profilesDir, `${profile}.${domain}.env`));
  }

  const merged = {};

  for (const file of envFiles) {
    try {
      const content = readFileSync(file, "utf-8");
      const lines = content.split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) continue;
        const [key, ...valueParts] = trimmed.split("=");
        const value = valueParts.join("=").trim();
        if (key) {
          merged[key] = value;
        }
      }
      console.log(`[env-loader] loaded ${file}`);
    } catch (error) {
      console.warn(`[env-loader] ${file} not found, skipping`);
    }
  }

  return merged;
}

function writeEnvLocal(envObj) {
  const envFile = resolve(webRoot, ".env.local");
  const lines = Object.entries(envObj)
    .map(([key, value]) => `${key}=${value}`)
    .sort();

  const header = `# Auto-generated by env-loader.mjs\n# Profile: ${parseArgs().profile}${parseArgs().domain ? ` | Domain: ${parseArgs().domain}` : ""}\n# Generated: ${new Date().toISOString()}\n\n`;
  writeFileSync(envFile, header + lines.join("\n") + "\n", "utf-8");
  console.log(`[env-loader] wrote ${envFile}`);
}

async function main() {
  const args = parseArgs();
  const profile = args.profile || process.env.ENV_PROFILE || "local";
  const domain = args.domain || process.env.DEPLOY_DOMAIN || null;

  console.log(`[env-loader] loading profile="${profile}" domain="${domain}"`);

  const envObj = loadProfileEnv(profile, domain);
  writeEnvLocal(envObj);

  console.log(`[env-loader] ${Object.keys(envObj).length} variables loaded`);
}

main().catch(console.error);

